### PR TITLE
Usul proposal events listeners

### LINKED ISSUE #779: Bug: Proposals list plural issue "1 transactions" should be "1 transaction"
### Overview

See screenshot

### Steps to reproduce

See list:

http://localhost:3000/#/daos/0xF332aAb56e00f7FDEdEDDC50033Ce5e2D0DD6d61/proposals

### Screenshots / Video

Screenshot 2022-12-13 at 4 09 37 PM

### Version

Dev (app.dev.fractalframework.xyz/)

### Browser

Firefox

### Operating System

Mac

### web3 wallet

None

### LINKED ISSUE #804: Add event listeners to Usul proposal events to reflect user actions

### PR DESCRIPTION
**Pull request by mudrila**
## Description

This PR implements chunk of event listeners for Usul-based proposal. 
It should cover pretty much all the interactions that are happening with proposal

## Notes
It also contains small fix for `proposalDescription` translation.

However, it does not contain page update when proposal state changed without even emitting. Like when voting timeline is passed (there's no specific event emitted, it is calculated via `state` func on `Usul` contract), as well when proposal goes from `Time Locked` state to `Executing` - there's no event/transaction/internal transaction happening. Possible workaround is adding `setTimeout` 🤔 

## Issue / Notion doc (if applicable)

Closes #804 
Closes #779 

## Testing

1. Create a proposal - you should see new proposal occured in the list shortly after creation. Proposal metadata should occur after that in a bit
2. Cast a vote on proposal. You should see your vote occured and breakdown change pretty much immediately after vote casted
3. Queue proposal. You should see status change reflection almost immediately
4. Execute proposal. You should see status change almost immediately after proposal execution

### CODE REVIEW

File: src/providers/Fractal/governance/hooks/useUsulProposals.ts [hunk 1]
```diff
@@ -48,21 +73,98 @@ export default function useUsulProposals({
         },
       });
     },
-    [usulContract, signerOrProvider, provider, governanceDispatch, txProposalsInfo]
+    [usulContract, signerOrProvider, provider, governanceDispatch, txProposalsInfo, chainId]
+  );
+
+  const proposalVotedEventListener: TypedListener<VotedEvent> = useCallback(
```
Comment (mobiusTripper-crypto) [inline src/providers/Fractal/governance/hooks/useUsulProposals.ts:79]: This might not be a good idea, but do you think it would be possible to combine this callback with `useUpdateProposalState.updateProposalState`? they look similar, but maybe different enough to keep separate?

**Review by mobiusTripper-crypto — APPROVED** [review]
couple comments, works great

File: src/i18n/locales/en/dashboard.json [hunk 2]
```diff
@@ -13,7 +13,8 @@
     "titlePassed": "Passed",
     "titleTreasury": "Treasury",
     "noActivity": "No Activity",
-    "proposalDescription": "Proposal to execute {{txCount}} transactions",
+    "proposalDescription_one": "Proposal to execute {{count}} transaction",
+    "proposalDescription_other": "Proposal to execute {{count}} transactions",
```
Comment (herbig) [inline src/i18n/locales/en/dashboard.json:17]: `proposalDescription` should be deleted in the UK json file

File: src/components/Proposals/UsulDetails/index.tsx [hunk 3]
```diff
@@ -1,18 +1,65 @@
...
+          () => updateProposalState(BigNumber.from(proposal.proposalNumber)),
+          timeout + 60000 // add extra 60 seconds to ensure that we woulnd't encounter issue while trying to update status in same minute as it supposed to change
+        )
+      );
+    }
+
+    return () => {
+      clearTimeout(activeTimeout);
+    };
+    // eslint-disable-next-line
```
Comment (herbig) [inline src/components/Proposals/UsulDetails/index.tsx:54]: I don't think this disable is needed

File: src/components/Proposals/UsulDetails/index.tsx [hunk 4]
```diff
@@ -1,18 +1,65 @@
...
+    if (proposal.state === TxProposalState.Active || proposal.state === TxProposalState.Pending) {
+      timeout = proposal.deadline * 1000 - now.getTime();
+    } else if (proposal.state === TxProposalState.TimeLocked) {
+      const timeLockNumber = timeLockPeriod?.value?.toNumber();
+      timeout =
+        new Date(proposal.deadline + Number(timeLockNumber) * 1000).getTime() - now.getTime();
+    }
+
+    // Prevent setting too large timer
+    if (timeout > 0 && timeout < 86400) {
```
Comment (herbig) [inline src/components/Proposals/UsulDetails/index.tsx:42]: not something we need to do here, but we should refactor all these time numbers to app constants at some point, like `DAY = 86400;`

Comment (herbig) [reply src/components/Proposals/UsulDetails/index.tsx:42]: or well in this case it's milliseconds.  Any reason you chose 86400?

**Review by herbig — APPROVED** [review]
looks good, I think we should delete the unused UK string now though

File: src/components/Proposals/UsulDetails/index.tsx (hunk 3 above)
Comment (herbig) [reply src/components/Proposals/UsulDetails/index.tsx:54]: oh scratch that, this was intentional
