### PR TITLE
Bug fixes

### LINKED ISSUE #1132: Proposal: Function Signature validation
Image

The validation for function signatures is tied to the parameters currently. So you can enter in a valid function signature but if your params aren't wrong it looks like the signature is invalid (even if it's valid).

We should make it more explicit (if we can) which field is invalid. If the validation can only occur with both, maybe the validation message can be updated to (signature or params are incorrect)

### LINKED ISSUE #1192: Bug: New proposals don't appear immediately after redirecting
### Overview

These should appear right away, or delay redirecting until they will

### Additional Info

_No response_

### Version

Dev (app.dev.fractalframework.xyz/)

### LINKED ISSUE #1200: Bug: Multisig proposals shows "Sign" button when I'm not a signer
### Overview

This was on the Decent Safe:

https://deploy-preview-1194--fractal-framework-interface-dev.netlify.app/daos/0xD26c85D435F02DaB8B220cd4D2d398f6f646e235/proposals

Screenshot 2023-06-02 at 1 02 24 PM

### Additional Info

_No response_

### Version

Dev (app.dev.fractalframework.xyz/)

### PR DESCRIPTION
**Pull request by mudrila**
## Description
This PR fixes bunch of bugs: #1192 #1132 #1200 

## Issue / Notion doc (if applicable)
Closes #1192 
Closes #1132 
Closes #1200

### CODE REVIEW

File: app/daos/[daoAddress]/proposals/page.tsx [hunk 1]
```diff
@@ -3,46 +3,30 @@
...
-    return false;
-  }, [type, azoriusGovernance]);
-
-  const showCreateButton = useMemo(
-    () =>
-      type === GovernanceModuleType.AZORIUS ? true : safe?.owners.includes(user.address || ''),
-    [type, safe, user.address]
-  );
+  const { canVote } = useCastVote({});
+  const { canUserCreateProposal } = useSubmitProposal();
```
Comment (herbig) [inline app/daos/[daoAddress]/proposals/page.tsx:29]: just looked at this `canUserCreateProposal`,  and that should rely on the Azorius strategy `isProposer(address _address)` function, not default to true...

That's a separate issue to this stuff though, I'll create a ticket for that.

File: src/components/Proposals/ProposalActions/Vote.tsx [hunk 2]
```diff
@@ -25,23 +24,18 @@ function Vote({
...
     proposalId: BigNumber.from(proposal.proposalId),
     setPending: setPending,
   });
 
   // if the user has no delegated tokens, don't show anything
-  if (
-    azoriusGovernance.votesToken.votingWeight &&
-    azoriusGovernance.votesToken?.votingWeight.eq(0)
-  ) {
+  if (canVote) {
```
Comment (herbig) [inline src/components/Proposals/ProposalActions/Vote.tsx:38]: yeah, we should have both _canDelegate_ and _canVote_ parameters, since they're different things but being used interchangebly here

File: src/i18n/locales/en/proposal.json [hunk 3]
```diff
@@ -45,7 +45,7 @@
     "createProposal": "Create Proposal",
     "labelAddTransaction": "+ Add Transaction",
     "buttonDelegate": "Delegate tokens",
-    "errorInvalidFragments": "Invalid function signature",
+    "errorInvalidFragments": "Invalid combination of function signature and parameters",
```
Comment (herbig) [inline src/i18n/locales/en/proposal.json:48]: yeah that's a quick fix for this, much clearer

**Review by herbig — CHANGES_REQUESTED** [review]
hey @mudrila had comment about separating `canVote` / `canDelegate`, also the can submit proposal was not accurate either, but it's fine for now so I created a ticket

https://github.com/decent-dao/fractal-interface/issues/1214

File: src/i18n/locales/en/proposal.json (hunk 3 above)
Comment (herbig) [reply src/i18n/locales/en/proposal.json:48]: @mudrila we should update or delete the UK translation for this as well, so they don't get out of sync

File: src/hooks/DAO/proposal/useCastVote.ts [hunk 4]
```diff
@@ -1,24 +1,44 @@
...
+        return safe.owners.includes(account);
+      } else if (governance.type === GovernanceModuleType.AZORIUS) {
+        const azoriusGovernance = governance as AzoriusGovernance;
+        if (azoriusGovernance.votesToken && azoriusGovernance.votesToken.balance) {
+          return azoriusGovernance.votesToken.balance.gt(0);
+        }
+      }
+    }
+    return false;
+  }, [account, governance, safe]);
```
[the remark this answers is not in the document]
Comment (herbig) [reply src/hooks/DAO/proposal/useCastVote.ts:36]: this also adds the delegate button to the multisig proposals page, which is incorrect

**Review by herbig — APPROVED** [review]
@mudrila I made some updates based on my code review, I think this fixes the issue now!
